"""Deterministic compatibility scoring between adopters and animals.

This module is the heart of the product decision recorded in spec section 8:
PetMatch must not depend on an unexplained number generated by a language
model. Every score here is computed by pure Python from database records, so
two identical inputs always produce an identical score, the arithmetic can be
shown to a user who asks "why 72?", and the whole suite tests offline.

The language model's job is to *explain* these numbers, never to produce
them. See docs/AGENT.md section 1.

Two directions exist because spec section 9 requires them to weigh things
differently:

    ADOPTER_TO_ANIMAL   what suits this person's life and stated preferences
    ANIMAL_TO_ADOPTER   what this animal's care needs and temperament require

The same pair can therefore score differently depending on which way round
the question is asked, which is the intended behaviour.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from app.domain.enums import (
    ActivityLevel,
    AnimalSize,
    ExperienceLevel,
    HomeType,
    MatchDirection,
    Species,
    Temperament,
)

PERFECT_SCORE = 100
NEUTRAL_SCORE = 60
MINIMUM_SCORE = 0

# The line between "worth highlighting" and "weak but still possible".
#
# This marks a pairing; it does not hide one. Ranking returns every candidate
# that clears the hard constraints, weakest last, because an adopter whose
# situation suits nothing well is better served by seeing modest matches with
# their scores than by an empty page that explains nothing. Staff see the same
# candidates, with the dashboard counting animals whose best applicant falls
# below this line as needing attention.
#
# 50 sits inside the reachable range rather than above it: a pairing that
# violates no hard constraint but fits badly in every soft criterion bottoms
# out near 30, so this genuinely separates candidates instead of flagging
# everyone or no one.
RECOMMENDATION_THRESHOLD = 50


class Criterion(StrEnum):
    """The matching criteria named in spec section 8."""

    LIVING_ENVIRONMENT = "living_environment"
    DAILY_AVAILABILITY = "daily_availability"
    EXPERIENCE_LEVEL = "experience_level"
    CHILDREN_COMPATIBILITY = "children_compatibility"
    OTHER_ANIMALS_COMPATIBILITY = "other_animals_compatibility"
    SIZE_AND_SPACE = "size_and_space"
    SPECIES_PREFERENCE = "species_preference"
    TEMPERAMENT_COMPATIBILITY = "temperament_compatibility"
    SPECIAL_CARE_CAPACITY = "special_care_capacity"
    AGE_PREFERENCE = "age_preference"
    LOCATION = "location"


# Spec section 9.1: the adopter's lifestyle and stated preferences lead.

class AgePreference(StrEnum):
    """The age bands an adopter can ask for (spec section 8).

    Bands rather than a number, because that is how people think about it:
    somebody wants "a puppy" or "an older, calmer one", not an animal
    between 2.0 and 8.0 years. `ANY` is a stated openness, not a missing
    answer - an adopter who picked it has told us something.
    """

    YOUNG = "0-2 years"
    ADULT = "2-8 years"
    SENIOR = "8+ years"
    ANY = "any"

    @property
    def includes_any_age(self) -> bool:
        """Whether this preference rules nothing out."""
        return self is AgePreference.ANY


# The boundaries each band covers, in years. Half-open at the top so the
# bands tile the whole range without overlapping.
AGE_BAND_BOUNDS: dict[AgePreference, tuple[float, float]] = {
    AgePreference.YOUNG: (0.0, 2.0),
    AgePreference.ADULT: (2.0, 8.0),
    AgePreference.SENIOR: (8.0, float("inf")),
}


ADOPTER_TO_ANIMAL_WEIGHTS: dict[Criterion, float] = {
    Criterion.SPECIES_PREFERENCE: 0.17,
    Criterion.LIVING_ENVIRONMENT: 0.15,
    Criterion.DAILY_AVAILABILITY: 0.13,
    Criterion.SIZE_AND_SPACE: 0.11,
    Criterion.TEMPERAMENT_COMPATIBILITY: 0.10,
    Criterion.AGE_PREFERENCE: 0.09,
    Criterion.EXPERIENCE_LEVEL: 0.08,
    Criterion.CHILDREN_COMPATIBILITY: 0.07,
    Criterion.OTHER_ANIMALS_COMPATIBILITY: 0.05,
    Criterion.SPECIAL_CARE_CAPACITY: 0.03,
    Criterion.LOCATION: 0.02,
}

# Spec section 9.2: the animal's care requirements lead, and may outrank what
# the person said they wanted. Note that species preference drops from the
# heaviest criterion to one of the lightest - from the animal's point of view
# it matters far less that someone *wanted* a cat than that they can meet the
# animal's actual needs.
ANIMAL_TO_ADOPTER_WEIGHTS: dict[Criterion, float] = {
    Criterion.DAILY_AVAILABILITY: 0.19,
    Criterion.EXPERIENCE_LEVEL: 0.17,
    Criterion.LIVING_ENVIRONMENT: 0.15,
    Criterion.SPECIAL_CARE_CAPACITY: 0.13,
    Criterion.SIZE_AND_SPACE: 0.11,
    Criterion.TEMPERAMENT_COMPATIBILITY: 0.09,
    Criterion.CHILDREN_COMPATIBILITY: 0.07,
    Criterion.OTHER_ANIMALS_COMPATIBILITY: 0.05,
    Criterion.AGE_PREFERENCE: 0.02,
    Criterion.SPECIES_PREFERENCE: 0.01,
    Criterion.LOCATION: 0.01,
}


@dataclass(frozen=True)
class AdopterFacts:
    """The adopter attributes matching depends on.

    A plain value object rather than the ORM model, so scoring can be tested
    with no database and the domain layer imports no framework (rule R2).
    """

    home_type: HomeType
    has_yard: bool
    household_has_children: bool
    youngest_child_age: int | None
    has_other_animals: bool
    experience_level: ExperienceLevel
    activity_level: ActivityLevel
    daily_hours_available: float
    city: str
    preferred_species: frozenset[Species]
    preferred_age_range: AgePreference | None = None
    preferred_size: AnimalSize | None = None
    open_to_proactive_suggestions: bool = False
    is_complete: bool = False


@dataclass(frozen=True)
class AnimalFacts:
    """The animal attributes matching depends on."""

    species: Species
    age_years: float
    size: AnimalSize
    temperament: Temperament
    activity_level: ActivityLevel
    good_with_children: bool
    good_with_other_animals: bool
    has_special_needs: bool
    required_space: AnimalSize
    city: str


@dataclass(frozen=True)
class CriterionScore:
    """One criterion's contribution to the total."""

    criterion: Criterion
    score: int
    weight: float
    explanation: str

    @property
    def weighted_contribution(self) -> float:
        """This criterion's share of the final score."""
        return self.score * self.weight


@dataclass(frozen=True)
class MatchScore:
    """The complete result of scoring one adopter against one animal."""

    direction: MatchDirection
    score: int
    is_disqualified: bool
    disqualification_reason: str | None
    criterion_scores: tuple[CriterionScore, ...]

    @property
    def is_recommended(self) -> bool:
        """Whether this pairing is strong enough to present."""
        return not self.is_disqualified and self.score >= RECOMMENDATION_THRESHOLD

    @classmethod
    def disqualified(cls, direction: MatchDirection, reason: str) -> MatchScore:
        """Build a disqualified result.

        A hard-constraint violation scores zero outright rather than merely
        reducing the total, so no combination of good soft scores can mask it
        (spec section 8).
        """
        return cls(
            direction=direction,
            score=MINIMUM_SCORE,
            is_disqualified=True,
            disqualification_reason=reason,
            criterion_scores=(),
        )


# --------------------------------------------------------------------------
# Hard constraints
# --------------------------------------------------------------------------

# Activity levels as numbers, so "how far apart are these?" is arithmetic
# rather than a nest of comparisons.
ACTIVITY_RANK = {ActivityLevel.LOW: 0, ActivityLevel.MODERATE: 1, ActivityLevel.HIGH: 2}
SIZE_RANK = {AnimalSize.SMALL: 0, AnimalSize.MEDIUM: 1, AnimalSize.LARGE: 2}
EXPERIENCE_RANK = {
    ExperienceLevel.NONE: 0,
    ExperienceLevel.SOME: 1,
    ExperienceLevel.EXPERIENCED: 2,
}

# Below this, a household with young children should not take an animal that
# is not certified good with children.
YOUNG_CHILD_AGE_LIMIT = 12

# A large animal in an apartment with no yard is a welfare problem, not a
# preference mismatch.
SPACE_HARD_LIMIT = {HomeType.APARTMENT: SIZE_RANK[AnimalSize.MEDIUM]}


def find_hard_constraint_violation(
    adopter: AdopterFacts, animal: AnimalFacts
) -> str | None:
    """Return the first hard-constraint violation, or None if there are none.

    Hard constraints express welfare and safety limits. Unlike soft
    preferences they cannot be traded off against a good score elsewhere.

    Args:
        adopter: The candidate adopter's facts.
        animal: The animal's facts.

    Returns:
        A human-readable reason, or None when the pairing is permissible.
    """
    if _has_unsafe_child_situation(adopter, animal):
        return (
            f"This animal is not suited to young children, and the household "
            f"includes a child aged {adopter.youngest_child_age}."
        )

    if adopter.has_other_animals and not animal.good_with_other_animals:
        return "This animal needs to be the only pet, and the household already has animals."

    if _has_insufficient_space(adopter, animal):
        return (
            f"A {animal.required_space.value.lower()} animal cannot be housed "
            f"in an apartment without a yard."
        )

    return None


def _has_unsafe_child_situation(adopter: AdopterFacts, animal: AnimalFacts) -> bool:
    """Whether placing this animal with this household would be unsafe for a child."""
    if animal.good_with_children:
        return False
    if not adopter.household_has_children:
        return False
    if adopter.youngest_child_age is None:
        # Children are present but their age is unknown. Treat the unknown as
        # the risky case rather than assuming it is fine.
        return True
    return adopter.youngest_child_age < YOUNG_CHILD_AGE_LIMIT


def _has_insufficient_space(adopter: AdopterFacts, animal: AnimalFacts) -> bool:
    """Whether the home is physically too small for the animal."""
    limit = SPACE_HARD_LIMIT.get(adopter.home_type)
    if limit is None:
        return False
    if adopter.has_yard:
        return False
    return SIZE_RANK[animal.required_space] > limit


# --------------------------------------------------------------------------
# Individual criteria - each pure, each independently testable
# --------------------------------------------------------------------------


def score_living_environment(adopter: AdopterFacts, animal: AnimalFacts) -> CriterionScore:
    """Score how well the home's type and outdoor space suit the animal."""
    space_gap = SIZE_RANK[animal.required_space] - _effective_home_capacity(adopter)

    if space_gap <= -1:
        score, explanation = PERFECT_SCORE, "The home offers more space than this animal needs."
    elif space_gap == 0:
        score, explanation = 90, "The home's space matches what this animal needs."
    elif space_gap == 1:
        score, explanation = 45, "The home is smaller than ideal for this animal."
    else:
        score, explanation = 15, "The home is considerably smaller than this animal needs."

    return CriterionScore(Criterion.LIVING_ENVIRONMENT, score, 0.0, explanation)


def _effective_home_capacity(adopter: AdopterFacts) -> int:
    """Rank the home's capacity on the same scale as animal size.

    A yard raises an apartment's effective capacity by one step, which is why
    capacity is computed rather than read directly from home type.
    """
    base_capacity = {
        HomeType.APARTMENT: SIZE_RANK[AnimalSize.SMALL],
        HomeType.HOUSE: SIZE_RANK[AnimalSize.MEDIUM],
        HomeType.FARM: SIZE_RANK[AnimalSize.LARGE],
    }[adopter.home_type]

    if adopter.has_yard:
        return min(base_capacity + 1, SIZE_RANK[AnimalSize.LARGE])
    return base_capacity


# Rough daily hours of attention each activity level implies.
REQUIRED_HOURS_BY_ACTIVITY = {
    ActivityLevel.LOW: 1.0,
    ActivityLevel.MODERATE: 2.5,
    ActivityLevel.HIGH: 4.0,
}


def score_daily_availability(adopter: AdopterFacts, animal: AnimalFacts) -> CriterionScore:
    """Score whether the adopter has enough time for this animal each day."""
    required_hours = REQUIRED_HOURS_BY_ACTIVITY[animal.activity_level]
    available_hours = adopter.daily_hours_available

    if available_hours >= required_hours:
        return CriterionScore(
            Criterion.DAILY_AVAILABILITY,
            PERFECT_SCORE,
            0.0,
            f"{available_hours:g} hours a day comfortably covers this animal's needs.",
        )

    shortfall_ratio = available_hours / required_hours
    score = max(MINIMUM_SCORE, int(PERFECT_SCORE * shortfall_ratio))
    return CriterionScore(
        Criterion.DAILY_AVAILABILITY,
        score,
        0.0,
        f"This animal needs about {required_hours:g} hours a day and "
        f"{available_hours:g} are available.",
    )


def score_experience_level(adopter: AdopterFacts, animal: AnimalFacts) -> CriterionScore:
    """Score whether the adopter's experience matches what the animal demands."""
    demand = _experience_demanded_by(animal)
    surplus = EXPERIENCE_RANK[adopter.experience_level] - demand

    if surplus >= 0:
        return CriterionScore(
            Criterion.EXPERIENCE_LEVEL,
            PERFECT_SCORE,
            0.0,
            "The adopter's experience meets what this animal requires.",
        )
    if surplus == -1:
        return CriterionScore(
            Criterion.EXPERIENCE_LEVEL,
            50,
            0.0,
            "This animal would benefit from a more experienced owner.",
        )
    return CriterionScore(
        Criterion.EXPERIENCE_LEVEL,
        20,
        0.0,
        "This animal needs an experienced owner and the adopter is a beginner.",
    )


def _experience_demanded_by(animal: AnimalFacts) -> int:
    """How much experience this animal realistically requires."""
    if animal.has_special_needs or animal.temperament is Temperament.ANXIOUS:
        return EXPERIENCE_RANK[ExperienceLevel.EXPERIENCED]
    if animal.activity_level is ActivityLevel.HIGH:
        return EXPERIENCE_RANK[ExperienceLevel.SOME]
    return EXPERIENCE_RANK[ExperienceLevel.NONE]


def score_children_compatibility(
    adopter: AdopterFacts, animal: AnimalFacts
) -> CriterionScore:
    """Score suitability for the children in the household.

    The unsafe combination is already a hard constraint, so this criterion
    grades the remaining, permissible cases.
    """
    if not adopter.household_has_children:
        return CriterionScore(
            Criterion.CHILDREN_COMPATIBILITY,
            PERFECT_SCORE,
            0.0,
            "No children in the household, so this is not a limiting factor.",
        )
    if animal.good_with_children:
        return CriterionScore(
            Criterion.CHILDREN_COMPATIBILITY,
            PERFECT_SCORE,
            0.0,
            "This animal is known to be good with children.",
        )
    return CriterionScore(
        Criterion.CHILDREN_COMPATIBILITY,
        40,
        0.0,
        "This animal is not certified as good with children; supervision would be needed.",
    )


def score_other_animals_compatibility(
    adopter: AdopterFacts, animal: AnimalFacts
) -> CriterionScore:
    """Score how the animal would fit alongside any existing pets.

    The outright incompatible case is already a hard constraint, so this
    criterion grades the permissible ones. Introducing an animal into a home
    that already has pets still carries real risk - the knowledge base notes
    that rushed introductions are the commonest cause of a failed multi-pet
    placement - so it scores below an empty household rather than equal to it.
    """
    if not adopter.has_other_animals:
        return CriterionScore(
            Criterion.OTHER_ANIMALS_COMPATIBILITY,
            PERFECT_SCORE,
            0.0,
            "No resident animals, so introductions are not a concern.",
        )

    if not animal.good_with_other_animals:
        # Unreachable through calculate_match_score, which checks hard
        # constraints first. Scored defensively so calling this function
        # directly cannot silently return a passing grade.
        return CriterionScore(
            Criterion.OTHER_ANIMALS_COMPATIBILITY,
            MINIMUM_SCORE,
            0.0,
            "This animal needs to be the only pet and the household has others.",
        )

    return CriterionScore(
        Criterion.OTHER_ANIMALS_COMPATIBILITY,
        80,
        0.0,
        "This animal gets on with others, though introductions will take weeks.",
    )


def score_size_and_space(adopter: AdopterFacts, animal: AnimalFacts) -> CriterionScore:
    """Score the animal's physical size against the home's capacity."""
    gap = SIZE_RANK[animal.size] - _effective_home_capacity(adopter)
    if gap <= 0:
        return CriterionScore(
            Criterion.SIZE_AND_SPACE, PERFECT_SCORE, 0.0,
            f"A {animal.size.value.lower()} animal fits this home comfortably.",
        )
    if gap == 1:
        return CriterionScore(
            Criterion.SIZE_AND_SPACE, 50, 0.0,
            f"A {animal.size.value.lower()} animal is large for this home.",
        )
    return CriterionScore(
        Criterion.SIZE_AND_SPACE, 20, 0.0,
        f"A {animal.size.value.lower()} animal is much larger than this home suits.",
    )


def score_species_preference(adopter: AdopterFacts, animal: AnimalFacts) -> CriterionScore:
    """Score whether this species is one the adopter said they wanted."""
    if not adopter.preferred_species:
        return CriterionScore(
            Criterion.SPECIES_PREFERENCE, NEUTRAL_SCORE, 0.0,
            "The adopter expressed no species preference.",
        )
    if animal.species in adopter.preferred_species:
        return CriterionScore(
            Criterion.SPECIES_PREFERENCE, PERFECT_SCORE, 0.0,
            f"The adopter is looking for a {animal.species.value.replace('_', ' ').lower()}.",
        )
    return CriterionScore(
        Criterion.SPECIES_PREFERENCE, 25, 0.0,
        "This species is not among the adopter's stated preferences.",
    )


def score_temperament_compatibility(
    adopter: AdopterFacts, animal: AnimalFacts
) -> CriterionScore:
    """Score how the animal's energy compares with the adopter's own."""
    distance = abs(ACTIVITY_RANK[animal.activity_level] - ACTIVITY_RANK[adopter.activity_level])

    if distance == 0:
        return CriterionScore(
            Criterion.TEMPERAMENT_COMPATIBILITY, PERFECT_SCORE, 0.0,
            "Adopter and animal share the same energy level.",
        )
    if distance == 1:
        return CriterionScore(
            Criterion.TEMPERAMENT_COMPATIBILITY, 65, 0.0,
            "Their energy levels differ somewhat but remain workable.",
        )
    return CriterionScore(
        Criterion.TEMPERAMENT_COMPATIBILITY, 25, 0.0,
        "Their energy levels are far apart, which often causes friction.",
    )


def score_special_care_capacity(
    adopter: AdopterFacts, animal: AnimalFacts
) -> CriterionScore:
    """Score the adopter's capacity to meet special-care requirements."""
    if not animal.has_special_needs:
        return CriterionScore(
            Criterion.SPECIAL_CARE_CAPACITY, PERFECT_SCORE, 0.0,
            "This animal has no special care requirements.",
        )
    if adopter.experience_level is ExperienceLevel.EXPERIENCED:
        return CriterionScore(
            Criterion.SPECIAL_CARE_CAPACITY, PERFECT_SCORE, 0.0,
            "The adopter is experienced enough for this animal's special needs.",
        )
    if adopter.experience_level is ExperienceLevel.SOME:
        return CriterionScore(
            Criterion.SPECIAL_CARE_CAPACITY, 55, 0.0,
            "This animal has special needs and the adopter has only some experience.",
        )
    return CriterionScore(
        Criterion.SPECIAL_CARE_CAPACITY, 20, 0.0,
        "This animal has special needs and the adopter has no prior experience.",
    )


def score_location(adopter: AdopterFacts, animal: AnimalFacts) -> CriterionScore:
    """Score practical proximity between adopter and animal."""
    if adopter.city.strip().lower() == animal.city.strip().lower():
        return CriterionScore(
            Criterion.LOCATION, PERFECT_SCORE, 0.0, "Adopter and animal are in the same city.",
        )
    return CriterionScore(
        Criterion.LOCATION, NEUTRAL_SCORE, 0.0,
        f"The animal is in {animal.city} and the adopter is in {adopter.city}.",
    )



def score_age_preference(adopter: AdopterFacts, animal: AnimalFacts) -> CriterionScore:
    """Score the animal's age against the band the adopter asked for.

    A soft preference, never a disqualification. Somebody who asked for a
    puppy and is shown a calm four-year-old may well change their mind, and
    an older animal being ranked lower is a fairer outcome than it being
    hidden.

    Scores partly rather than in a step: an adopter wanting 2-8 years is
    better served by a 1.5-year-old than by a 12-year-old, and a flat
    "outside the band" score would call those two the same.
    """
    preference = adopter.preferred_age_range
    if preference is None:
        return CriterionScore(
            Criterion.AGE_PREFERENCE, NEUTRAL_SCORE, 0.0,
            "The adopter expressed no age preference.",
        )

    if preference.includes_any_age:
        return CriterionScore(
            Criterion.AGE_PREFERENCE, PERFECT_SCORE, 0.0,
            "The adopter is open to an animal of any age.",
        )

    lower, upper = AGE_BAND_BOUNDS[preference]
    if lower <= animal.age_years < upper:
        return CriterionScore(
            Criterion.AGE_PREFERENCE, PERFECT_SCORE, 0.0,
            f"At {_age_in_words(animal.age_years)}, this animal is in the "
            f"{preference.value} range the adopter asked for.",
        )

    distance = lower - animal.age_years if animal.age_years < lower else animal.age_years - upper
    return CriterionScore(
        Criterion.AGE_PREFERENCE,
        _score_from_age_distance(distance),
        0.0,
        f"The adopter asked for {preference.value}, and this animal is "
        f"{_age_in_words(animal.age_years)}.",
    )


# How far outside the requested band an animal is, and what that is worth.
# Ordered nearest first; the first band the distance fits decides the score.
# Graded rather than a cliff-edge, so "a year older than they asked for" and
# "a decade older" are not treated as the same miss.
AGE_DISTANCE_SCORES: tuple[tuple[float, int], ...] = (
    (1.0, 75),
    (3.0, 55),
    (6.0, 35),
)
FAR_OUTSIDE_AGE_BAND_SCORE = 20


def _score_from_age_distance(years_outside_band: float) -> int:
    """Turn a distance outside the requested band into a score."""
    for limit, score in AGE_DISTANCE_SCORES:
        if years_outside_band <= limit:
            return score
    return FAR_OUTSIDE_AGE_BAND_SCORE


def _age_in_words(age_years: float) -> str:
    """Describe an age the way an explanation should read."""
    if age_years < 1:
        months = max(1, round(age_years * 12))
        return f"{months} month{'s' if months != 1 else ''} old"
    whole = int(age_years)
    return f"{whole} year{'s' if whole != 1 else ''} old"


ALL_CRITERION_FUNCTIONS = {
    Criterion.LIVING_ENVIRONMENT: score_living_environment,
    Criterion.DAILY_AVAILABILITY: score_daily_availability,
    Criterion.EXPERIENCE_LEVEL: score_experience_level,
    Criterion.CHILDREN_COMPATIBILITY: score_children_compatibility,
    Criterion.OTHER_ANIMALS_COMPATIBILITY: score_other_animals_compatibility,
    Criterion.SIZE_AND_SPACE: score_size_and_space,
    Criterion.SPECIES_PREFERENCE: score_species_preference,
    Criterion.TEMPERAMENT_COMPATIBILITY: score_temperament_compatibility,
    Criterion.SPECIAL_CARE_CAPACITY: score_special_care_capacity,
    Criterion.AGE_PREFERENCE: score_age_preference,
    Criterion.LOCATION: score_location,
}


# --------------------------------------------------------------------------
# Public entry points
# --------------------------------------------------------------------------


def calculate_match_score(
    adopter: AdopterFacts, animal: AnimalFacts, direction: MatchDirection
) -> MatchScore:
    """Score one adopter against one animal in the requested direction.

    Reads as the specification does: check hard constraints, score each
    criterion, then combine using the weights for this direction.

    Args:
        adopter: The adopter's facts.
        animal: The animal's facts.
        direction: Which weighting to apply. The two directions deliberately
            differ (spec section 9).

    Returns:
        The score with its full per-criterion breakdown. Disqualified results
        carry a reason and an empty breakdown.
    """
    violation = find_hard_constraint_violation(adopter, animal)
    if violation is not None:
        return MatchScore.disqualified(direction, violation)

    weights = weights_for(direction)
    scored_criteria = tuple(
        _apply_weight(ALL_CRITERION_FUNCTIONS[criterion](adopter, animal), weight)
        for criterion, weight in weights.items()
    )

    total = sum(criterion.weighted_contribution for criterion in scored_criteria)

    return MatchScore(
        direction=direction,
        score=round(total),
        is_disqualified=False,
        disqualification_reason=None,
        criterion_scores=scored_criteria,
    )


def weights_for(direction: MatchDirection) -> dict[Criterion, float]:
    """Return the weight set for a direction."""
    if direction is MatchDirection.ADOPTER_TO_ANIMAL:
        return ADOPTER_TO_ANIMAL_WEIGHTS
    return ANIMAL_TO_ADOPTER_WEIGHTS


def _apply_weight(criterion_score: CriterionScore, weight: float) -> CriterionScore:
    """Attach the direction's weight to a criterion result.

    Criterion functions do not know which direction they are being used for,
    which keeps each one testable in isolation.
    """
    return CriterionScore(
        criterion=criterion_score.criterion,
        score=criterion_score.score,
        weight=weight,
        explanation=criterion_score.explanation,
    )


def rank_animals_for_adopter(
    adopter: AdopterFacts, animals: dict[str, AnimalFacts]
) -> list[tuple[str, MatchScore]]:
    """Rank animals for one adopter, best first (Find My Pet).

    Args:
        adopter: The adopter's facts.
        animals: Animal facts keyed by animal identifier.

    Returns:
        Identifier and score pairs, disqualified candidates excluded, ordered
        by descending score then by identifier so ties are stable.
    """
    return _rank(
        {key: calculate_match_score(adopter, facts, MatchDirection.ADOPTER_TO_ANIMAL)
         for key, facts in animals.items()}
    )


def rank_adopters_for_animal(
    animal: AnimalFacts, adopters: dict[str, AdopterFacts]
) -> list[tuple[str, MatchScore]]:
    """Rank adopters for one animal, best first (Find My Adopter).

    Args:
        animal: The animal's facts.
        adopters: Adopter facts keyed by adopter profile identifier.

    Returns:
        Identifier and score pairs, disqualified candidates excluded, ordered
        by descending score then by identifier so ties are stable.
    """
    return _rank(
        {key: calculate_match_score(facts, animal, MatchDirection.ANIMAL_TO_ADOPTER)
         for key, facts in adopters.items()}
    )


def _rank(scores: dict[str, MatchScore]) -> list[tuple[str, MatchScore]]:
    """Drop disqualified candidates and order the rest deterministically.

    Ties break on the identifier so that repeated runs over the same data
    produce the same order - important for stable screenshots and tests.
    """
    qualified = [(key, score) for key, score in scores.items() if not score.is_disqualified]
    return sorted(qualified, key=lambda pair: (-pair[1].score, pair[0]))
